import React, { useState } from 'react';
import { Sparkles, Image as ImageIcon, Download, Share2, Paintbrush } from 'lucide-react';
import { generateCampaignPoster } from '../services/geminiService';

interface CreativeStudioProps {
  onClose: () => void;
}

const CreativeStudio: React.FC<CreativeStudioProps> = ({ onClose }) => {
  const [prompt, setPrompt] = useState('');
  const [style, setStyle] = useState('Modern Minimalist');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!prompt) return;
    setIsGenerating(true);
    const result = await generateCampaignPoster(prompt, style);
    setGeneratedImage(result);
    setIsGenerating(false);
  };

  const styles = ['Modern Minimalist', 'Vintage Humanitarian', 'Bold & Urgent', 'Hand-drawn Community'];

  return (
    <div className="flex flex-col h-full p-6 pb-24 overflow-y-auto">
      <div className="mb-6">
        <h2 className="text-2xl font-bold flex items-center gap-2">
            <Paintbrush className="w-6 h-6 text-pink-500" />
            Creative Autopilot
        </h2>
        <p className="text-slate-500 text-sm mt-1">
            Generate professional posters for your missions. Power your campaigns with multimodal AI.
        </p>
      </div>

      <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100 space-y-6">
        <div>
            <label className="block text-sm font-bold text-slate-700 mb-2">What is your campaign about?</label>
            <textarea 
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g., A food drive at Central Park this Saturday..."
                className="w-full p-4 bg-slate-50 rounded-xl border border-slate-200 focus:ring-2 focus:ring-pink-500 focus:outline-none"
                rows={3}
            />
        </div>

        <div>
            <label className="block text-sm font-bold text-slate-700 mb-2">Visual Style</label>
            <div className="flex gap-2 flex-wrap">
                {styles.map(s => (
                    <button 
                        key={s}
                        onClick={() => setStyle(s)}
                        className={`px-3 py-2 rounded-lg text-xs font-bold transition-colors ${style === s ? 'bg-pink-100 text-pink-700 border border-pink-200' : 'bg-slate-50 text-slate-600 border border-slate-200'}`}
                    >
                        {s}
                    </button>
                ))}
            </div>
        </div>

        <button 
            onClick={handleGenerate}
            disabled={isGenerating || !prompt}
            className="w-full bg-slate-900 text-white py-4 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-slate-800 disabled:opacity-50 transition-colors"
        >
            {isGenerating ? <Sparkles className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
            {isGenerating ? 'Designing...' : 'Generate Assets'}
        </button>
      </div>

      {/* Result Area */}
      {generatedImage && (
          <div className="mt-8 bg-white p-4 rounded-2xl shadow-lg border border-slate-200 animate-in fade-in slide-in-from-bottom-4">
              <h3 className="font-bold text-slate-900 mb-4 flex items-center gap-2">
                  <ImageIcon className="w-5 h-5 text-pink-500" /> Generated Asset
              </h3>
              <div className="aspect-[3/4] w-full bg-slate-100 rounded-xl overflow-hidden mb-4 relative group">
                  <img src={generatedImage} alt="Generated Campaign" className="w-full h-full object-cover" />
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
                      <button className="p-3 bg-white rounded-full hover:scale-110 transition-transform"><Download className="w-5 h-5 text-slate-900" /></button>
                      <button className="p-3 bg-white rounded-full hover:scale-110 transition-transform"><Share2 className="w-5 h-5 text-slate-900" /></button>
                  </div>
              </div>
              <p className="text-xs text-slate-400 text-center">Generated by Gemini 3 Pro • Usage Rights: Public Domain</p>
          </div>
      )}
    </div>
  );
};

export default CreativeStudio;