/**
 * DESIGN SYSTEM COMPONENT EXAMPLES
 * Generated by UI/UX Pro Max
 * 
 * This file demonstrates how to use the new design system components.
 * Copy these examples into your views to upgrade the UI.
 */

import React from 'react';
import { Button, Badge, Card, ProgressBar } from './components';
import { Zap, Users, Trophy, MapPin } from 'lucide-react';

// ============================================
// EXAMPLE 1: Mission Card with New Components
// ============================================
export const MissionCardExample = ({ mission }) => (
    <Card variant="mission" hoverable>
        <div className="flex justify-between items-start mb-4">
            <h3 className="font-heading text-xl text-gray-900">{mission.title}</h3>
            <Badge variant={mission.status === 'active' ? 'active' : 'completed'}>
                {mission.status}
            </Badge>
        </div>

        <p className="text-gray-600 mb-4">{mission.description}</p>

        <ProgressBar
            current={mission.currentProgress}
            max={mission.totalGoal}
            label="Progress"
            variant="gradient"
        />

        <div className="flex justify-between items-center mt-4">
            <div className="flex items-center gap-2 text-cta">
                <Zap className="w-5 h-5" />
                <span className="font-semibold">+{mission.xp} XP</span>
            </div>
            <Button variant="primary" size="md">
                Accept Mission
            </Button>
        </div>
    </Card>
);

// ============================================
// EXAMPLE 2: Profile Stats Card
// ============================================
export const ProfileStatsExample = ({ user }) => (
    <Card variant="profile">
        <div className="space-y-4">
            <div className="flex items-center justify-between">
                <h2 className="font-heading text-2xl">Level {user.level}</h2>
                <Badge variant="trustScore">
                    Trust Score: {user.trustScore}
                </Badge>
            </div>

            <ProgressBar
                current={user.xp}
                max={user.nextLevelXP}
                label="XP to Next Level"
                variant="gradient"
            />

            <div className="grid grid-cols-3 gap-4 mt-6">
                <div className="text-center">
                    <Trophy className="w-8 h-8 mx-auto text-primary mb-2" />
                    <p className="font-heading text-2xl">{user.completedMissions}</p>
                    <p className="text-sm text-gray-600">Missions</p>
                </div>
                <div className="text-center">
                    <Zap className="w-8 h-8 mx-auto text-cta mb-2" />
                    <p className="font-heading text-2xl">{user.totalXP}</p>
                    <p className="text-sm text-gray-600">Total XP</p>
                </div>
                <div className="text-center">
                    <Users className="w-8 h-8 mx-auto text-success mb-2" />
                    <p className="font-heading text-2xl">{user.recruitsCount}</p>
                    <p className="text-sm text-gray-600">Recruits</p>
                </div>
            </div>
        </div>
    </Card>
);

// ============================================
// EXAMPLE 3: Streak Display
// ============================================
export const StreakExample = ({ streakDays }) => (
    <Card variant="stats" className="text-center">
        <div className="inline-flex items-center gap-3">
            <div className="relative">
                <div className="w-16 h-16 bg-gradient-to-br from-orange-400 to-orange-600 rounded-full flex items-center justify-center animate-pulse-dot">
                    <span className="text-3xl">🔥</span>
                </div>
            </div>
            <div className="text-left">
                <p className="font-heading text-4xl text-orange-600">{streakDays}</p>
                <p className="text-sm font-semibold uppercase tracking-wide text-gray-600">Day Streak</p>
            </div>
        </div>
    </Card>
);

// ============================================
// EXAMPLE 4: Emergency Swarm Mode Button
// ============================================
export const SwarmModeExample = ({ onActivate }) => (
    <div className="fixed bottom-6 right-6 z-50">
        <Button
            variant="emergency"
            size="lg"
            onClick={onActivate}
            className="shadow-2xl"
        >
            <span className="text-2xl mr-2">🚨</span>
            ACTIVATE SWARM MODE
        </Button>
    </div>
);

// ============================================
// EXAMPLE 5: Skill Tree Node
// ============================================
export const SkillNodeExample = ({ skill, unlocked }) => (
    <div className="relative">
        <div
            className={`
        w-20 h-20 rounded-full flex items-center justify-center
        transition-all cursor-pointer
        ${unlocked
                    ? 'bg-gradient-to-br from-cta to-primary shadow-lg hover:scale-110'
                    : 'bg-gray-300 opacity-50'
                }
      `}
        >
            <Trophy className={`w-8 h-8 ${unlocked ? 'text-white' : 'text-gray-500'}`} />
        </div>
        <p className={`text-xs mt-2 text-center font-semibold ${unlocked ? 'text-gray-900' : 'text-gray-400'}`}>
            {skill.name}
        </p>
        {unlocked && (
            <Badge variant="completed" className="absolute -top-2 -right-2 text-xs">
                ✓
            </Badge>
        )}
    </div>
);

// ============================================
// EXAMPLE 6: Location Pin with Active Mission
// ============================================
export const ActiveMissionPinExample = ({ mission }) => (
    <div className="inline-flex items-center gap-2 bg-white rounded-full shadow-lg px-4 py-2">
        <div className="relative">
            <MapPin className="w-6 h-6 text-error" />
            <span className="absolute -top-1 -right-1 w-3 h-3 bg-error rounded-full animate-pulse-ring" />
        </div>
        <div>
            <p className="font-semibold text-sm">{mission.location}</p>
            <Badge variant="urgent" className="text-xs">
                {mission.activeVolunteers} en route
            </Badge>
        </div>
    </div>
);

// ============================================
// EXAMPLE 7: Button Variants Showcase
// ============================================
export const ButtonShowcase = () => (
    <div className="flex flex-wrap gap-4">
        <Button variant="primary">Primary Action</Button>
        <Button variant="secondary">Secondary Action</Button>
        <Button variant="success">Mark Complete</Button>
        <Button variant="emergency">Emergency</Button>

        <Button variant="primary" size="sm">Small</Button>
        <Button variant="primary" size="md">Medium</Button>
        <Button variant="primary" size="lg">Large</Button>

        <Button variant="primary" disabled>Disabled</Button>
    </div>
);

// ============================================
// EXAMPLE 8: Badge Variants Showcase
// ============================================
export const BadgeShowcase = () => (
    <div className="flex flex-wrap gap-3">
        <Badge variant="active">Active Mission</Badge>
        <Badge variant="completed">Completed</Badge>
        <Badge variant="streak">🔥 7 Day Streak</Badge>
        <Badge variant="trustScore">Trust: 94</Badge>
        <Badge variant="pending">Pending Approval</Badge>
        <Badge variant="urgent">Urgent</Badge>
    </div>
);

// ============================================
// USAGE IN YOUR VIEWS
// ============================================

/**
 * TO USE THESE COMPONENTS IN YOUR EXISTING VIEWS:
 * 
 * 1. Import at the top of your file:
 *    import { Button, Badge, Card, ProgressBar } from '../components';
 *    import { Zap, Trophy, Users } from 'lucide-react';
 * 
 * 2. Replace existing JSX:
 * 
 *    OLD:
 *    <button className="bg-blue-500 text-white px-4 py-2 rounded">
 *      Accept
 *    </button>
 * 
 *    NEW:
 *    <Button variant="primary">Accept</Button>
 * 
 * 3. For mission cards, replace entire card markup with:
 *    <MissionCardExample mission={missionData} />
 * 
 * 4. Icons: Lucide is already in your importmap, so just import:
 *    import { Zap, Trophy, Users, MapPin, Clock } from 'lucide-react';
 */
